---
name: Enhancement Request
description: Template to submit a enhancement request against CatC as Code
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the enhancement is.
      placeholder: Tell us what you want to see!
    validations:
      required: true

  - type: checkboxes
    id: catc-version
    attributes:
      label: CatC Version
      description: Specify the Catalyst Center version related to the enhancement.
      options:
        - label: CatC 2.3.7.6
        - label: CatC 2.3.7.7
        - label: CatC 2.3.7.9
        - label: CatC 2.3.7.10
        - label: CatC 3.1.x
        - label: CatC 3.2.x
    validations:
      required: false

  - type: input
    id: customer-name
    attributes:
      label: Associated Customer
      description: Provide customer name if applicable.
      placeholder: Customer name
    validations:
      required: true

  - type: dropdown
    id: services-as-code
    attributes:
      label: Is this a customer of Services as Code (LCS)?
      description: Is the issue opened for a customer with paid Services as Code support?
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true

  - type: input
    id: customer-pid
    attributes:
      label: Project PID/DID
      description: Provide Project PID or deal ID to prioritize the issue.
      placeholder: Project Project PID or deal ID
    validations:
      required: false
